# main configuration file
# key=value

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=kh16
spring.datasource.password=kh16

# dbcp (database connection pool)
spring.datasource.dbcp2.max-total=20
#spring.datasource.dbcp2.min-idle=5
spring.datasource.dbcp2.max-idle=5

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#server
#server.servlet.context-path=/kh16
#server.port=7777

#springdoc
springdoc.api-docs.enabled=true
springdoc.packages-to-scan=com.kh.spring10.restcontroller
springdoc.swagger-ui.path=/api.html

#myBatis
mybatis.type-aliases-package=com.kh.spring10.dto,com.kh.spring10.vo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=/mybatis/**/*-mapper.xml
mybatis.configuration.jdbc-type-for-null=null

#Custom-properties
custom.jwt.key-str=nodvicdkzkepal12#nodvicdkzkepal12#nodvicdkzkepal12#
custom.jwt.issuer=KHAcademy
custom.jwt.expiration=30
custom.jwt.refresh-expiration=28
custom.jwt.renewal-limit=10

custom.email.username=nodvicsemi
custom.email.password=zxhiobqclqvkctqw 

#logging
logging.level.root=WARN
logging.level.com.kh=DEBUG
#logging.level.account=DEBUG